
import java.awt.Container;
import java.awt.PopupMenu;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        ButtonBangun2D = new javax.swing.JButton();
        ButtonBangun3D = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonBangun2D.setText("Bangun 2D");
        ButtonBangun2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBangun2DActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonBangun2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 30));

        ButtonBangun3D.setText("Bangun 3D");
        ButtonBangun3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBangun3DActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonBangun3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, 30));

        jTabbedPane2.addTab("Bangun Geometri", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBangun2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBangun2DActionPerformed
        // 1. Buat JTabbedPane baru
        JTabbedPane tabbedPaneBaru = new JTabbedPane();

        // 2. Tambahkan tab contoh
        JPanel panelBaru = new JPanel();
        panelBaru.add(new JLabel("Isi Bangun 2D")); // Konten bisa diganti
        tabbedPaneBaru.addTab("2D", panelBaru);

        // 3. Tambahkan ke JFrame (gunakan JPanel sebagai container)
        // Hapus semua komponen yang ada dari contentPane
        getContentPane().removeAll();

        // Atur layout horizontal
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.X_AXIS));

        // Tambahkan jTabbedPane2 (yang awal) dan tabbedPaneBaru
        getContentPane().add(jTabbedPane2);
        getContentPane().add(tabbedPaneBaru);

        // 4. Refresh frame
        revalidate();
        repaint();
    }//GEN-LAST:event_ButtonBangun2DActionPerformed

    private void ButtonBangun3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBangun3DActionPerformed

        // 1. Buat JTabbedPane baru
        JTabbedPane tabbedPaneBaru = new JTabbedPane();

        // 2. Tambahkan tab contoh
        JPanel panelBaru = new JPanel();
        panelBaru.add(new JLabel("Isi Bangun 3D")); // Konten bisa diganti
        tabbedPaneBaru.addTab("3D", panelBaru);

        // 3. Tambahkan ke JFrame (gunakan JPanel sebagai container)
        // Hapus semua komponen yang ada dari contentPane
        getContentPane().removeAll();

        // Atur layout horizontal
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.X_AXIS));

        // Tambahkan jTabbedPane2 (yang awal) dan tabbedPaneBaru
        getContentPane().add(jTabbedPane2);
        getContentPane().add(tabbedPaneBaru);

        // 4. Refresh frame
        revalidate();
        repaint();
    
    }//GEN-LAST:event_ButtonBangun3DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {

            new NewJFrame().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBangun2D;
    private javax.swing.JButton ButtonBangun3D;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
